---
abstract: ~
author:
  - 'Masayoshi Sekimura <sekimura@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Prowl
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Crypt::SSLeay: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
